version: '3.9'
services:
  mongodb:
    container_name: db-credits-transactions
    image: mongo
    hostname: host-bank
    restart: always
    ports:
      - "27022:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hrevilla
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - data-credits-transactions:/data/db
    networks:
      - bank

volumes:
  data-credits-transactions:
    name: data-credits-transactions

networks:
  bank:
    name: bank